version: "3.8"

networks:
  web_api:
    name: web_api

services:
  web:
    container_name: api
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "5555:5555"
      - "7070:7070"
    environment:
      - PORT=5000
    depends_on:
      - postgesql
      - redis
    restart: always
    volumes:
      - ./:/app
    networks:
      - web_api

  redis:
    image: redis:7.0-alpine
    container_name: api_redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - web_api

  postgresql:
    image: postgres:12.12
    container_name: api_postgesql
    ports:
      - "5433:5432"
    restart: always
    environment:
      - POSTGRES_USER=pasha
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - web_api

  jaeger:
    container_name: jaeger_container
    image: jaegertracing/all-in-one:1.21
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
    networks:
      - web_api